nelmio_api_doc:
    documentation:
        servers:
          - url: http://localhost:8000/
            description: API over HTTP
          - url: https://localhost:8000/
            description: API over HTTPS
        info:
            title: Pet Addict
            description: Find your animal partner!
            version: 1.0.0-SNAPSHOT
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []